//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_App_With_Images.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Web;

    public partial class employee2
    {
        public int id { get; set; }

        [DisplayName("Employee Name")]
        [Required(ErrorMessage ="Name is Required")]
        public string name { get; set; }

        [DisplayName("Employee Designation")]
        [Required(ErrorMessage = "Designation is Required")]
        public string designaton { get; set; }


        [DisplayName("Employee Mobile ")]
        [Required(ErrorMessage = "Mobile is Required")]
        public long mobile { get; set; }


        [DisplayName("Employee Images")]
        public string image_path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
